safe: true
markdown: kramdown
permalink: pretty
sitetagline: 'CivicPatterns.org is a collection of patterns and tools that help Civic Technology projects succeed.' 
cats:
- Community
- Delivery
- Government
- Engagement
